import { PrismaClient, PlanTier } from '@prisma/client';
import * as bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');
  await seedPlans();
  await seedRolesAndPermissions();
  await seedCategories();
  await seedTools();
  await seedAdminUser();
  console.log('✅ Seeding complete.');
}

// ─── Plans ────────────────────────────────────────────────────────────────────

async function seedPlans() {
  const plans = [
    {
      name: 'Free', tier: PlanTier.free,
      description: 'Get started with AI tools at no cost.',
      monthlyPriceUsd: 0, yearlyPriceUsd: 0,
      creditsPerMonth: 100, maxGenerations: 100,
      features: ['100 credits/month', '20+ AI tools', 'GPT-3.5 model', 'Community support'],
      stripePriceIdMonthly: null, stripePriceIdYearly: null,
      sortOrder: 0,
    },
    {
      name: 'Starter', tier: PlanTier.starter,
      description: 'Perfect for individuals and freelancers.',
      monthlyPriceUsd: 9.99, yearlyPriceUsd: 7.99,
      creditsPerMonth: 1000, maxGenerations: 1000,
      features: ['1,000 credits/month', '60+ AI tools', 'GPT-4o model', 'History & favorites', '10 image prompts/month', 'Email support'],
      stripePriceIdMonthly: process.env.STRIPE_PRICE_STARTER_MONTHLY ?? null,
      stripePriceIdYearly:  process.env.STRIPE_PRICE_STARTER_YEARLY  ?? null,
      sortOrder: 1,
    },
    {
      name: 'Pro', tier: PlanTier.pro,
      description: 'For power users and small teams.',
      monthlyPriceUsd: 29.99, yearlyPriceUsd: 19.99,
      creditsPerMonth: 5000, maxGenerations: null,
      features: ['5,000 credits/month', '100+ AI tools', 'All AI models (GPT-4o, Claude)', '100 image prompts/month', 'API access', 'Priority support', 'Advanced analytics'],
      stripePriceIdMonthly: process.env.STRIPE_PRICE_PRO_MONTHLY ?? null,
      stripePriceIdYearly:  process.env.STRIPE_PRICE_PRO_YEARLY  ?? null,
      sortOrder: 2,
    },
    {
      name: 'Business', tier: PlanTier.enterprise,
      description: 'Custom solutions for large teams.',
      monthlyPriceUsd: 99.99, yearlyPriceUsd: 79.99,
      creditsPerMonth: 999999, maxGenerations: null,
      features: ['Unlimited credits', 'All Pro features', 'Unlimited image prompts', 'Custom AI fine-tuning', 'Unlimited team seats', 'SSO / SAML', 'SLA guarantee', 'Dedicated support'],
      stripePriceIdMonthly: process.env.STRIPE_PRICE_BUSINESS_MONTHLY ?? null,
      stripePriceIdYearly:  process.env.STRIPE_PRICE_BUSINESS_YEARLY  ?? null,
      sortOrder: 3,
    },
  ];
  for (const plan of plans) {
    await prisma.plan.upsert({ where: { tier: plan.tier }, update: plan, create: plan });
  }
  console.log('  ✓ Plans seeded');
}

// ─── Roles & Permissions ──────────────────────────────────────────────────────

async function seedRolesAndPermissions() {
  const permissions = [
    { action: 'manage', subject: 'all', description: 'Full access to everything' },
    { action: 'create', subject: 'Tool', description: 'Create AI tools' },
    { action: 'read',   subject: 'Tool', description: 'Read AI tools' },
    { action: 'update', subject: 'Tool', description: 'Update AI tools' },
    { action: 'delete', subject: 'Tool', description: 'Delete AI tools' },
    { action: 'create', subject: 'Category', description: 'Create categories' },
    { action: 'update', subject: 'Category', description: 'Update categories' },
    { action: 'delete', subject: 'Category', description: 'Delete categories' },
    { action: 'read',   subject: 'User', description: 'Read user data' },
    { action: 'update', subject: 'User', description: 'Update user data' },
    { action: 'delete', subject: 'User', description: 'Delete users' },
    { action: 'manage', subject: 'Subscription', description: 'Manage subscriptions' },
    { action: 'manage', subject: 'Credits', description: 'Manage credits' },
    { action: 'read',   subject: 'AdminLog', description: 'Read audit logs' },
  ];
  for (const perm of permissions) {
    await prisma.permission.upsert({ where: { action_subject: { action: perm.action, subject: perm.subject } }, update: { description: perm.description }, create: perm });
  }
  const adminRole = await prisma.role.upsert({ where: { name: 'admin' }, update: { description: 'Full platform administrator', isSystem: true }, create: { name: 'admin', description: 'Full platform administrator', isSystem: true } });
  const userRole  = await prisma.role.upsert({ where: { name: 'user'  }, update: { description: 'Standard authenticated user',  isSystem: true }, create: { name: 'user',  description: 'Standard authenticated user',  isSystem: true } });
  const manageAll = await prisma.permission.findUnique({ where: { action_subject: { action: 'manage', subject: 'all'  } } });
  const readTool  = await prisma.permission.findUnique({ where: { action_subject: { action: 'read',   subject: 'Tool' } } });
  if (manageAll) await prisma.rolePermission.upsert({ where: { roleId_permissionId: { roleId: adminRole.id, permissionId: manageAll.id } }, update: {}, create: { roleId: adminRole.id, permissionId: manageAll.id } });
  if (readTool)  await prisma.rolePermission.upsert({ where: { roleId_permissionId: { roleId: userRole.id,  permissionId: readTool.id  } }, update: {}, create: { roleId: userRole.id,  permissionId: readTool.id  } });
  console.log('  ✓ Roles & permissions seeded');
}

// ─── Categories ───────────────────────────────────────────────────────────────

async function seedCategories() {
  const categories = [
    { name: 'Writing & Content',    slug: 'writing-content',    description: 'Blog posts, articles, copywriting and content creation tools.',                    color: '#6366f1', sortOrder: 0 },
    { name: 'Code & Development',   slug: 'code-development',   description: 'Code generation, debugging, documentation and dev tools.',                         color: '#0ea5e9', sortOrder: 1 },
    { name: 'Business & Strategy',  slug: 'business-strategy',  description: 'Business plans, SWOT analysis, pitch decks and strategy tools.',                   color: '#10b981', sortOrder: 2 },
    { name: 'Email & Communication',slug: 'email-communication', description: 'Email drafts, subject lines, replies and communication tools.',                    color: '#f97316', sortOrder: 3 },
    { name: 'Education & Learning', slug: 'education-learning', description: 'Lesson plans, quizzes, summaries and learning tools.',                              color: '#14b8a6', sortOrder: 4 },
    { name: 'Marketing',            slug: 'marketing',          description: 'Facebook ads, Google ads, marketing plans, CTAs, slogans and brand tools.',         color: '#f43f5e', sortOrder: 5 },
    { name: 'SEO',                  slug: 'seo',                description: 'Keyword research, meta tags, SEO articles, schema markup and optimisation tools.',  color: '#22c55e', sortOrder: 6 },
    { name: 'Social Media',         slug: 'social-media',       description: 'Posts, captions, scripts, hashtags and content calendar tools.',                    color: '#a855f7', sortOrder: 7 },
    { name: 'Image & Design',        slug: 'image-design',       description: 'AI image prompts, product visuals, ad creatives and design brief tools.',           color: '#f59e0b', sortOrder: 8 },
    { name: 'Productivity',          slug: 'productivity',        description: 'Meeting summaries, task generation, brainstorming and decision-making tools.',      color: '#06b6d4', sortOrder: 9 },
  ];
  for (const cat of categories) {
    await prisma.category.upsert({ where: { slug: cat.slug }, update: { name: cat.name, description: cat.description, color: cat.color, sortOrder: cat.sortOrder }, create: cat });
  }
  console.log('  ✓ Categories seeded');
}

// ─── Tool type ────────────────────────────────────────────────────────────────

type ToolSeed = {
  name: string; slug: string; description: string; shortDescription: string;
  categorySlug: string; tags: string[]; isPremium: boolean; isFeatured: boolean; sortOrder: number;
  config: { systemPrompt: string; userPromptTemplate: string; inputSchema: object; outputFormat: string; aiModel: string; maxTokens: number; temperature: number; creditCost: number };
};

// ─── AI Tools ─────────────────────────────────────────────────────────────────

async function seedTools() {
  const categoryMap = await prisma.category.findMany().then(cats => Object.fromEntries(cats.map(c => [c.slug, c.id])));
  const tools: ToolSeed[] = [...writingTools(), ...marketingTools(), ...seoTools(), ...socialTools(), ...imageTools(), ...codeExtendedTools(), ...productivityTools(), ...otherTools()];

  for (const tool of tools) {
    const categoryId = categoryMap[tool.categorySlug];
    if (!categoryId) { console.warn(`  ⚠ Category not found: ${tool.categorySlug}`); continue; }
    const created = await prisma.aITool.upsert({
      where: { slug: tool.slug },
      update: { name: tool.name, description: tool.description, shortDescription: tool.shortDescription, categoryId, tags: tool.tags, isPremium: tool.isPremium, isFeatured: tool.isFeatured, sortOrder: tool.sortOrder },
      create: { name: tool.name, slug: tool.slug, description: tool.description, shortDescription: tool.shortDescription, categoryId, tags: tool.tags, isPremium: tool.isPremium, isFeatured: tool.isFeatured, sortOrder: tool.sortOrder },
    });
    await prisma.toolConfiguration.upsert({
      where: { toolId: created.id },
      update: { ...tool.config },
      create: { toolId: created.id, ...tool.config },
    });
  }
  console.log(`  ✓ ${tools.length} AI tools seeded`);
}

// ─── Writing Tools ────────────────────────────────────────────────────────────

function writingTools(): ToolSeed[] {
  return [
    { name: 'AI Blog Writer', slug: 'ai-blog-writer', description: 'Generate full SEO-optimised blog posts from a title, keywords, and tone.', shortDescription: 'Write complete blog posts in seconds.', categorySlug: 'writing-content', tags: ['blog','writing','seo','content'], isPremium: false, isFeatured: true, sortOrder: 0,
      config: { systemPrompt: 'You are an expert content writer who creates engaging, SEO-optimised blog posts. Use proper H2/H3 headings, short paragraphs, and a compelling introduction and conclusion.', userPromptTemplate: 'Write a comprehensive blog post about: {{topic}}\n\nTarget keywords: {{keywords}}\nTone: {{tone}}\nTarget word count: {{wordCount}} words', inputSchema: { type:'object', required:['topic'], properties:{ topic:{type:'string',title:'Blog Topic',placeholder:'e.g. 10 tips for remote work productivity'}, keywords:{type:'string',title:'Target Keywords',placeholder:'e.g. remote work, productivity'}, tone:{type:'string',title:'Tone',enum:['professional','casual','humorous','authoritative'],default:'professional'}, wordCount:{type:'string',title:'Word Count',enum:['500','800','1200','1500'],default:'800'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:2048, temperature:0.7, creditCost:3 } },
    { name: 'AI Article Writer', slug: 'ai-article-writer', description: 'Write in-depth, well-researched articles on any topic with a structured format.', shortDescription: 'Create in-depth articles on any topic.', categorySlug: 'writing-content', tags: ['article','writing','research','journalism'], isPremium: false, isFeatured: true, sortOrder: 1,
      config: { systemPrompt: 'You are a professional journalist and article writer. Write well-structured, factual, and engaging articles with a clear thesis, supporting arguments, and a strong conclusion.', userPromptTemplate: 'Write a detailed article about: {{topic}}\n\nAngle/Focus: {{angle}}\nAudience: {{audience}}\nTone: {{tone}}', inputSchema: { type:'object', required:['topic'], properties:{ topic:{type:'string',title:'Article Topic',placeholder:'e.g. The future of renewable energy'}, angle:{type:'string',title:'Angle or Focus',placeholder:'e.g. economic impact'}, audience:{type:'string',title:'Target Audience',placeholder:'e.g. business professionals'}, tone:{type:'string',title:'Tone',enum:['informative','analytical','persuasive','neutral'],default:'informative'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:2048, temperature:0.6, creditCost:3 } },
    { name: 'AI Rewriter', slug: 'ai-rewriter', description: 'Rewrite any text to improve clarity, style, or tone while preserving meaning.', shortDescription: 'Rewrite text with improved style and clarity.', categorySlug: 'writing-content', tags: ['rewrite','editing','clarity','style'], isPremium: false, isFeatured: false, sortOrder: 2,
      config: { systemPrompt: 'You are an expert editor. Rewrite the provided text to improve its clarity, flow, and style while preserving the original meaning and intent.', userPromptTemplate: 'Rewrite the following text:\n\n{{text}}\n\nRewrite goal: {{goal}}\nTone: {{tone}}', inputSchema: { type:'object', required:['text'], properties:{ text:{type:'string',title:'Text to Rewrite',placeholder:'Paste your text here...'}, goal:{type:'string',title:'Rewrite Goal',enum:['improve clarity','make more formal','make more casual','make more concise','make more engaging'],default:'improve clarity'}, tone:{type:'string',title:'Output Tone',enum:['professional','casual','academic','conversational'],default:'professional'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:1024, temperature:0.5, creditCost:1 } },
    { name: 'AI Summarizer', slug: 'ai-summarizer', description: 'Summarize any long text, article, or document into clear, concise key points.', shortDescription: 'Summarize any text instantly.', categorySlug: 'writing-content', tags: ['summary','reading','notes','research'], isPremium: false, isFeatured: false, sortOrder: 3,
      config: { systemPrompt: 'You are an expert at distilling complex information into clear, concise summaries. Preserve the key ideas and important details while removing fluff.', userPromptTemplate: 'Summarize the following text:\n\n{{text}}\n\nSummary length: {{length}}\nFormat: {{format}}', inputSchema: { type:'object', required:['text'], properties:{ text:{type:'string',title:'Text to Summarize',placeholder:'Paste the text you want to summarize...'}, length:{type:'string',title:'Summary Length',enum:['brief (3-5 sentences)','medium (1 paragraph)','detailed (3 paragraphs)'],default:'medium (1 paragraph)'}, format:{type:'string',title:'Output Format',enum:['paragraph','bullet points'],default:'bullet points'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:512, temperature:0.3, creditCost:1 } },
    { name: 'AI Paraphraser', slug: 'ai-paraphraser', description: 'Paraphrase any text to express the same ideas in a completely different way.', shortDescription: 'Paraphrase text while keeping the meaning.', categorySlug: 'writing-content', tags: ['paraphrase','rewrite','plagiarism','editing'], isPremium: false, isFeatured: false, sortOrder: 4,
      config: { systemPrompt: 'You are a skilled paraphrasing expert. Rewrite the provided text using different words and sentence structures while keeping the exact same meaning.', userPromptTemplate: 'Paraphrase the following text:\n\n{{text}}\n\nStyle: {{style}}', inputSchema: { type:'object', required:['text'], properties:{ text:{type:'string',title:'Text to Paraphrase',placeholder:'Paste your text here...'}, style:{type:'string',title:'Paraphrase Style',enum:['standard','fluency','formal','simple','creative'],default:'standard'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:1024, temperature:0.6, creditCost:1 } },
    { name: 'Grammar Checker', slug: 'grammar-checker', description: 'Check and correct grammar, spelling, punctuation, and style errors in any text.', shortDescription: 'Fix grammar and spelling errors instantly.', categorySlug: 'writing-content', tags: ['grammar','spelling','proofreading','editing'], isPremium: false, isFeatured: false, sortOrder: 5,
      config: { systemPrompt: 'You are a professional proofreader and grammar expert. Identify and correct all grammar, spelling, punctuation, and style errors. Return the corrected text followed by a list of changes made.', userPromptTemplate: 'Check and correct the grammar in the following text:\n\n{{text}}\n\nReturn the corrected version followed by a brief list of corrections made.', inputSchema: { type:'object', required:['text'], properties:{ text:{type:'string',title:'Text to Check',placeholder:'Paste your text here to check for grammar errors...'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:1024, temperature:0.1, creditCost:1 } },
    { name: 'Email Writer', slug: 'email-writer', description: 'Draft professional emails for any situation — follow-ups, pitches, apologies, and more.', shortDescription: 'Write professional emails fast.', categorySlug: 'email-communication', tags: ['email','professional','communication','business'], isPremium: false, isFeatured: true, sortOrder: 0,
      config: { systemPrompt: 'You are a professional business communication expert. Write clear, concise, and effective emails that achieve their intended purpose. Include a subject line.', userPromptTemplate: 'Write a professional email:\n\nPurpose: {{purpose}}\nRecipient: {{recipient}}\nKey points to cover: {{points}}\nTone: {{tone}}', inputSchema: { type:'object', required:['purpose'], properties:{ purpose:{type:'string',title:'Email Purpose',placeholder:'e.g. Follow up on a job application'}, recipient:{type:'string',title:'Recipient',placeholder:'e.g. Hiring Manager'}, points:{type:'string',title:'Key Points to Cover',placeholder:'e.g. Mention interview date, express enthusiasm'}, tone:{type:'string',title:'Tone',enum:['formal','semi-formal','casual'],default:'semi-formal'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:512, temperature:0.6, creditCost:1 } },
    { name: 'Product Description', slug: 'product-description', description: 'Create compelling product descriptions that convert browsers into buyers.', shortDescription: 'Write product descriptions that sell.', categorySlug: 'writing-content', tags: ['ecommerce','product','copywriting','sales'], isPremium: false, isFeatured: false, sortOrder: 6,
      config: { systemPrompt: 'You are a conversion-focused copywriter specialising in product descriptions. Highlight benefits over features, use sensory language, and include a clear call to action.', userPromptTemplate: 'Write a product description for: {{productName}}\n\nKey features: {{features}}\nTarget audience: {{audience}}\nTone: {{tone}}', inputSchema: { type:'object', required:['productName','features'], properties:{ productName:{type:'string',title:'Product Name',placeholder:'e.g. Wireless Noise-Cancelling Headphones'}, features:{type:'string',title:'Key Features',placeholder:'e.g. 30hr battery, active noise cancellation'}, audience:{type:'string',title:'Target Audience',placeholder:'e.g. remote workers, commuters'}, tone:{type:'string',title:'Tone',enum:['professional','casual','luxury','playful'],default:'professional'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:512, temperature:0.7, creditCost:1 } },
    { name: 'Headline Generator', slug: 'headline-generator', description: 'Generate attention-grabbing headlines for blogs, ads, emails, and landing pages.', shortDescription: 'Create headlines that get clicks.', categorySlug: 'writing-content', tags: ['headline','title','copywriting','seo'], isPremium: false, isFeatured: false, sortOrder: 7,
      config: { systemPrompt: 'You are a headline writing expert. Generate multiple compelling, click-worthy headlines using proven formulas (how-to, listicle, question, curiosity gap, benefit-driven).', userPromptTemplate: 'Generate 10 headlines for:\n\nTopic: {{topic}}\nContent type: {{contentType}}\nTarget audience: {{audience}}', inputSchema: { type:'object', required:['topic'], properties:{ topic:{type:'string',title:'Topic',placeholder:'e.g. productivity tips for entrepreneurs'}, contentType:{type:'string',title:'Content Type',enum:['blog post','email subject','ad headline','landing page','social post'],default:'blog post'}, audience:{type:'string',title:'Target Audience',placeholder:'e.g. small business owners'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:512, temperature:0.8, creditCost:1 } },
    { name: 'Story Generator', slug: 'story-generator', description: 'Generate creative short stories from a premise, genre, and characters.', shortDescription: 'Create original short stories instantly.', categorySlug: 'writing-content', tags: ['creative','fiction','storytelling','narrative'], isPremium: false, isFeatured: false, sortOrder: 8,
      config: { systemPrompt: 'You are a creative fiction writer. Craft engaging stories with vivid descriptions, compelling characters, rising tension, and satisfying narrative arcs.', userPromptTemplate: 'Write a short story with this premise: {{premise}}\n\nGenre: {{genre}}\nMain character: {{character}}\nLength: {{length}}', inputSchema: { type:'object', required:['premise'], properties:{ premise:{type:'string',title:'Story Premise',placeholder:'e.g. A detective discovers their partner is the killer'}, genre:{type:'string',title:'Genre',enum:['fantasy','sci-fi','romance','thriller','horror','comedy','mystery'],default:'thriller'}, character:{type:'string',title:'Main Character',placeholder:'e.g. A retired detective named Sarah'}, length:{type:'string',title:'Length',enum:['short (300 words)','medium (600 words)','long (1000 words)'],default:'medium (600 words)'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:1500, temperature:0.9, creditCost:2 } },
  ];
}

// ─── Marketing Tools ──────────────────────────────────────────────────────────

function marketingTools(): ToolSeed[] {
  return [
    { name: 'Facebook Ad Generator', slug: 'facebook-ad-generator', description: 'Generate high-converting Facebook ad copy with headlines, body text, and CTAs.', shortDescription: 'Create Facebook ads that convert.', categorySlug: 'marketing', tags: ['facebook','ads','social','marketing','ppc'], isPremium: false, isFeatured: true, sortOrder: 0,
      config: { systemPrompt: 'You are a Facebook Ads expert and direct-response copywriter. Write compelling ad copy that stops the scroll, speaks to the target audience pain points, and drives clicks. Include primary text, headline, and a CTA.', userPromptTemplate: 'Write a Facebook ad for:\n\nProduct/Service: {{product}}\nTarget audience: {{audience}}\nMain benefit: {{benefit}}\nOffer/CTA: {{cta}}\nTone: {{tone}}', inputSchema: { type:'object', required:['product','audience'], properties:{ product:{type:'string',title:'Product or Service',placeholder:'e.g. Online fitness coaching program'}, audience:{type:'string',title:'Target Audience',placeholder:'e.g. Women aged 25-40 who want to lose weight'}, benefit:{type:'string',title:'Main Benefit',placeholder:'e.g. Lose 10kg in 90 days'}, cta:{type:'string',title:'Call to Action',placeholder:'e.g. Sign up for free trial',default:'Learn More'}, tone:{type:'string',title:'Tone',enum:['urgent','friendly','professional','bold'],default:'friendly'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:512, temperature:0.7, creditCost:2 } },
    { name: 'Google Ad Generator', slug: 'google-ad-generator', description: 'Create Google Search ads with headlines and descriptions optimised for Quality Score.', shortDescription: 'Write Google ads that rank and convert.', categorySlug: 'marketing', tags: ['google','ads','ppc','search','marketing'], isPremium: false, isFeatured: true, sortOrder: 1,
      config: { systemPrompt: 'You are a Google Ads specialist. Write responsive search ad copy with 3 headlines (max 30 chars each) and 2 descriptions (max 90 chars each). Include the target keyword naturally and a strong CTA.', userPromptTemplate: 'Write Google Search ads for:\n\nProduct/Service: {{product}}\nTarget keyword: {{keyword}}\nUnique selling point: {{usp}}\nLanding page goal: {{goal}}', inputSchema: { type:'object', required:['product','keyword'], properties:{ product:{type:'string',title:'Product or Service',placeholder:'e.g. Cloud accounting software'}, keyword:{type:'string',title:'Target Keyword',placeholder:'e.g. accounting software for small business'}, usp:{type:'string',title:'Unique Selling Point',placeholder:'e.g. Free 30-day trial, no credit card'}, goal:{type:'string',title:'Landing Page Goal',enum:['sign up','buy now','get quote','book demo','download'],default:'sign up'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:512, temperature:0.6, creditCost:2 } },
    { name: 'Marketing Plan', slug: 'marketing-plan', description: 'Generate a comprehensive marketing plan with goals, channels, tactics, and KPIs.', shortDescription: 'Build a full marketing plan in minutes.', categorySlug: 'marketing', tags: ['marketing','strategy','plan','business'], isPremium: true, isFeatured: true, sortOrder: 2,
      config: { systemPrompt: 'You are a senior marketing strategist. Create detailed, actionable marketing plans with clear objectives, target audience analysis, channel strategy, content plan, budget allocation, and measurable KPIs.', userPromptTemplate: 'Create a marketing plan for:\n\nBusiness: {{business}}\nProduct/Service: {{product}}\nTarget market: {{market}}\nBudget: {{budget}}\nTimeframe: {{timeframe}}', inputSchema: { type:'object', required:['business','product'], properties:{ business:{type:'string',title:'Business Name/Type',placeholder:'e.g. SaaS startup for project management'}, product:{type:'string',title:'Product or Service',placeholder:'e.g. Team collaboration tool'}, market:{type:'string',title:'Target Market',placeholder:'e.g. Remote teams of 10-50 people'}, budget:{type:'string',title:'Monthly Budget',placeholder:'e.g. $5,000'}, timeframe:{type:'string',title:'Timeframe',enum:['1 month','3 months','6 months','12 months'],default:'3 months'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:2048, temperature:0.6, creditCost:4 } },
    { name: 'CTA Generator', slug: 'cta-generator', description: 'Generate powerful calls-to-action for landing pages, emails, ads, and buttons.', shortDescription: 'Create CTAs that drive action.', categorySlug: 'marketing', tags: ['cta','conversion','copywriting','marketing'], isPremium: false, isFeatured: false, sortOrder: 3,
      config: { systemPrompt: 'You are a conversion rate optimisation expert. Generate multiple compelling calls-to-action that create urgency, communicate value, and drive the desired action.', userPromptTemplate: 'Generate 10 CTAs for:\n\nProduct/Service: {{product}}\nDesired action: {{action}}\nPlacement: {{placement}}\nTone: {{tone}}', inputSchema: { type:'object', required:['product','action'], properties:{ product:{type:'string',title:'Product or Service',placeholder:'e.g. Email marketing tool'}, action:{type:'string',title:'Desired Action',placeholder:'e.g. Start free trial'}, placement:{type:'string',title:'Placement',enum:['landing page button','email','popup','ad','social post'],default:'landing page button'}, tone:{type:'string',title:'Tone',enum:['urgent','friendly','bold','professional'],default:'bold'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:512, temperature:0.8, creditCost:1 } },
    { name: 'Slogan Generator', slug: 'slogan-generator', description: 'Create memorable brand slogans and taglines that stick in customers minds.', shortDescription: 'Generate catchy slogans for your brand.', categorySlug: 'marketing', tags: ['slogan','tagline','branding','marketing'], isPremium: false, isFeatured: false, sortOrder: 4,
      config: { systemPrompt: 'You are a brand strategist and creative copywriter. Generate memorable, concise slogans that capture the brand essence, resonate with the target audience, and are easy to remember.', userPromptTemplate: 'Generate 10 slogans for:\n\nBrand/Product: {{brand}}\nCore value/benefit: {{value}}\nTarget audience: {{audience}}\nTone: {{tone}}', inputSchema: { type:'object', required:['brand','value'], properties:{ brand:{type:'string',title:'Brand or Product Name',placeholder:'e.g. FreshBrew Coffee'}, value:{type:'string',title:'Core Value or Benefit',placeholder:'e.g. Premium coffee that energises your day'}, audience:{type:'string',title:'Target Audience',placeholder:'e.g. Young professionals'}, tone:{type:'string',title:'Tone',enum:['fun','professional','inspirational','bold','minimalist'],default:'bold'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:512, temperature:0.9, creditCost:1 } },
    { name: 'Brand Name Generator', slug: 'brand-name-generator', description: 'Generate unique, memorable brand names with domain availability suggestions.', shortDescription: 'Find the perfect name for your brand.', categorySlug: 'marketing', tags: ['branding','naming','startup','business'], isPremium: false, isFeatured: false, sortOrder: 5,
      config: { systemPrompt: 'You are a brand naming expert. Generate creative, memorable, and unique brand names that are easy to pronounce, spell, and remember. For each name, briefly explain the concept behind it.', userPromptTemplate: 'Generate 10 brand names for:\n\nBusiness type: {{businessType}}\nCore offering: {{offering}}\nTarget audience: {{audience}}\nStyle preference: {{style}}', inputSchema: { type:'object', required:['businessType','offering'], properties:{ businessType:{type:'string',title:'Business Type',placeholder:'e.g. AI productivity SaaS'}, offering:{type:'string',title:'Core Offering',placeholder:'e.g. Automates repetitive tasks for teams'}, audience:{type:'string',title:'Target Audience',placeholder:'e.g. Startup founders'}, style:{type:'string',title:'Name Style',enum:['modern & tech','classic & trustworthy','fun & playful','abstract','descriptive'],default:'modern & tech'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:512, temperature:0.9, creditCost:1 } },
    { name: 'Email Campaign', slug: 'email-campaign', description: 'Write a complete email marketing campaign sequence for any product or goal.', shortDescription: 'Create full email campaign sequences.', categorySlug: 'marketing', tags: ['email','campaign','marketing','sequence','newsletter'], isPremium: true, isFeatured: false, sortOrder: 6,
      config: { systemPrompt: 'You are an email marketing expert. Write compelling email campaign sequences with strong subject lines, engaging body copy, and clear CTAs. Each email should build on the previous one.', userPromptTemplate: 'Write an email campaign for:\n\nProduct/Service: {{product}}\nCampaign goal: {{goal}}\nTarget audience: {{audience}}\nNumber of emails: {{count}}\nTone: {{tone}}', inputSchema: { type:'object', required:['product','goal'], properties:{ product:{type:'string',title:'Product or Service',placeholder:'e.g. Online course on digital marketing'}, goal:{type:'string',title:'Campaign Goal',enum:['launch product','nurture leads','re-engage subscribers','promote sale','onboard users'],default:'launch product'}, audience:{type:'string',title:'Target Audience',placeholder:'e.g. Small business owners'}, count:{type:'string',title:'Number of Emails',enum:['3','5','7'],default:'3'}, tone:{type:'string',title:'Tone',enum:['professional','conversational','urgent','friendly'],default:'conversational'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:2048, temperature:0.7, creditCost:4 } },
  ];
}

// ─── SEO Tools ────────────────────────────────────────────────────────────────

function seoTools(): ToolSeed[] {
  return [
    { name: 'Keyword Generator', slug: 'keyword-generator', description: 'Generate targeted keyword lists with search intent for any topic or niche.', shortDescription: 'Find the best keywords for your content.', categorySlug: 'seo', tags: ['seo','keywords','research','traffic'], isPremium: false, isFeatured: true, sortOrder: 0,
      config: { systemPrompt: 'You are an SEO keyword research expert. Generate comprehensive keyword lists organised by search intent (informational, navigational, commercial, transactional). Include long-tail variations and related terms.', userPromptTemplate: 'Generate keywords for:\n\nTopic/Niche: {{topic}}\nBusiness type: {{businessType}}\nTarget country: {{country}}\nKeyword type: {{keywordType}}', inputSchema: { type:'object', required:['topic'], properties:{ topic:{type:'string',title:'Topic or Niche',placeholder:'e.g. home office furniture'}, businessType:{type:'string',title:'Business Type',placeholder:'e.g. ecommerce store'}, country:{type:'string',title:'Target Country',placeholder:'e.g. United States',default:'United States'}, keywordType:{type:'string',title:'Keyword Type',enum:['all types','informational','commercial','transactional','long-tail'],default:'all types'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:1024, temperature:0.4, creditCost:2 } },
    { name: 'Meta Title Generator', slug: 'meta-title-generator', description: 'Generate SEO-optimised meta titles under 60 characters that improve click-through rates.', shortDescription: 'Write perfect meta titles for SEO.', categorySlug: 'seo', tags: ['seo','meta','title','search'], isPremium: false, isFeatured: false, sortOrder: 1,
      config: { systemPrompt: 'You are an SEO expert specialising in meta tags. Generate compelling meta titles that are 50-60 characters, include the target keyword naturally, and maximise click-through rates from search results.', userPromptTemplate: 'Generate 5 meta titles for:\n\nPage topic: {{topic}}\nTarget keyword: {{keyword}}\nBrand name: {{brand}}\nPage type: {{pageType}}', inputSchema: { type:'object', required:['topic','keyword'], properties:{ topic:{type:'string',title:'Page Topic',placeholder:'e.g. Best project management tools for remote teams'}, keyword:{type:'string',title:'Target Keyword',placeholder:'e.g. project management tools'}, brand:{type:'string',title:'Brand Name',placeholder:'e.g. Acme Inc (optional)'}, pageType:{type:'string',title:'Page Type',enum:['blog post','product page','homepage','category page','landing page'],default:'blog post'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:256, temperature:0.6, creditCost:1 } },
    { name: 'Meta Description Generator', slug: 'meta-description-generator', description: 'Write compelling meta descriptions under 160 characters that boost CTR from search results.', shortDescription: 'Create meta descriptions that get clicks.', categorySlug: 'seo', tags: ['seo','meta','description','search'], isPremium: false, isFeatured: false, sortOrder: 2,
      config: { systemPrompt: 'You are an SEO expert. Write meta descriptions that are 150-160 characters, include the target keyword, summarise the page value, and include a subtle CTA to improve click-through rates.', userPromptTemplate: 'Generate 5 meta descriptions for:\n\nPage topic: {{topic}}\nTarget keyword: {{keyword}}\nKey benefit: {{benefit}}\nPage type: {{pageType}}', inputSchema: { type:'object', required:['topic','keyword'], properties:{ topic:{type:'string',title:'Page Topic',placeholder:'e.g. Guide to remote work productivity'}, keyword:{type:'string',title:'Target Keyword',placeholder:'e.g. remote work productivity'}, benefit:{type:'string',title:'Key Benefit',placeholder:'e.g. Actionable tips to double your output'}, pageType:{type:'string',title:'Page Type',enum:['blog post','product page','homepage','category page','landing page'],default:'blog post'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:256, temperature:0.6, creditCost:1 } },
    { name: 'SEO Article Writer', slug: 'seo-article-writer', description: 'Write fully SEO-optimised articles with proper keyword density, headings, and structure.', shortDescription: 'Write SEO articles that rank on Google.', categorySlug: 'seo', tags: ['seo','article','content','ranking'], isPremium: true, isFeatured: true, sortOrder: 3,
      config: { systemPrompt: 'You are an SEO content writer. Write fully optimised articles with the target keyword in the title, first paragraph, H2 headings, and naturally throughout. Use LSI keywords, short paragraphs, and include an FAQ section.', userPromptTemplate: 'Write an SEO-optimised article:\n\nTarget keyword: {{keyword}}\nTopic: {{topic}}\nWord count: {{wordCount}}\nSearch intent: {{intent}}', inputSchema: { type:'object', required:['keyword','topic'], properties:{ keyword:{type:'string',title:'Target Keyword',placeholder:'e.g. best CRM software for small business'}, topic:{type:'string',title:'Article Topic',placeholder:'e.g. Top 10 CRM tools reviewed'}, wordCount:{type:'string',title:'Word Count',enum:['800','1200','1500','2000'],default:'1200'}, intent:{type:'string',title:'Search Intent',enum:['informational','commercial','transactional'],default:'informational'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:2500, temperature:0.6, creditCost:4 } },
    { name: 'SEO Content Outline', slug: 'seo-content-outline', description: 'Generate a detailed SEO content outline with H2/H3 headings, key points, and word counts.', shortDescription: 'Plan SEO content with a detailed outline.', categorySlug: 'seo', tags: ['seo','outline','content','planning'], isPremium: false, isFeatured: false, sortOrder: 4,
      config: { systemPrompt: 'You are an SEO content strategist. Create detailed content outlines with H1, H2, H3 headings, key points for each section, suggested word counts, and internal linking opportunities.', userPromptTemplate: 'Create an SEO content outline for:\n\nTarget keyword: {{keyword}}\nContent type: {{contentType}}\nCompetitor angle to beat: {{angle}}\nTarget word count: {{wordCount}}', inputSchema: { type:'object', required:['keyword'], properties:{ keyword:{type:'string',title:'Target Keyword',placeholder:'e.g. how to start a podcast'}, contentType:{type:'string',title:'Content Type',enum:['how-to guide','listicle','comparison','review','pillar page'],default:'how-to guide'}, angle:{type:'string',title:'Unique Angle',placeholder:'e.g. focus on budget-friendly equipment'}, wordCount:{type:'string',title:'Target Word Count',enum:['800','1200','1500','2000','3000'],default:'1500'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:1024, temperature:0.5, creditCost:2 } },
    { name: 'Keyword Clustering', slug: 'keyword-clustering', description: 'Group a list of keywords into topical clusters for better content strategy and site architecture.', shortDescription: 'Cluster keywords into content topics.', categorySlug: 'seo', tags: ['seo','keywords','clustering','strategy'], isPremium: true, isFeatured: false, sortOrder: 5,
      config: { systemPrompt: 'You are an SEO strategist specialising in topical authority. Group the provided keywords into logical clusters based on search intent and topic similarity. For each cluster, suggest a pillar page title and supporting content ideas.', userPromptTemplate: 'Cluster these keywords into topical groups:\n\nKeywords:\n{{keywords}}\n\nNiche/Industry: {{niche}}', inputSchema: { type:'object', required:['keywords'], properties:{ keywords:{type:'string',title:'Keywords (one per line)',placeholder:'e.g.\nbest running shoes\nrunning shoes for beginners\nhow to choose running shoes\nrunning shoe brands'}, niche:{type:'string',title:'Niche or Industry',placeholder:'e.g. fitness and sports'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:1024, temperature:0.4, creditCost:2 } },
    { name: 'Schema Generator', slug: 'schema-generator', description: 'Generate JSON-LD schema markup for articles, products, FAQs, and local businesses.', shortDescription: 'Create schema markup for rich snippets.', categorySlug: 'seo', tags: ['seo','schema','json-ld','structured-data'], isPremium: false, isFeatured: false, sortOrder: 6,
      config: { systemPrompt: 'You are a technical SEO expert. Generate valid JSON-LD schema markup following Schema.org standards. Output only the complete, valid JSON-LD code block ready to paste into a webpage.', userPromptTemplate: 'Generate {{schemaType}} schema markup for:\n\nName/Title: {{name}}\nDescription: {{description}}\nAdditional details: {{details}}', inputSchema: { type:'object', required:['schemaType','name'], properties:{ schemaType:{type:'string',title:'Schema Type',enum:['Article','Product','FAQ','LocalBusiness','Recipe','Event','Review','HowTo'],default:'Article'}, name:{type:'string',title:'Name or Title',placeholder:'e.g. How to Make Perfect Sourdough Bread'}, description:{type:'string',title:'Description',placeholder:'e.g. A step-by-step guide to baking sourdough'}, details:{type:'string',title:'Additional Details',placeholder:'e.g. Author: John Doe, Published: 2024-01-01'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:1024, temperature:0.1, creditCost:1 } },
    { name: 'Internal Link Suggestions', slug: 'internal-link-suggestions', description: 'Get internal linking suggestions to improve site structure and distribute page authority.', shortDescription: 'Find internal linking opportunities.', categorySlug: 'seo', tags: ['seo','internal-links','site-structure','authority'], isPremium: false, isFeatured: false, sortOrder: 7,
      config: { systemPrompt: 'You are an SEO expert specialising in internal linking strategy. Analyse the provided content and suggest relevant internal linking opportunities with anchor text recommendations that improve topical authority and user experience.', userPromptTemplate: 'Suggest internal links for this content:\n\nPage topic: {{topic}}\nTarget keyword: {{keyword}}\nExisting pages on site:\n{{existingPages}}\n\nContent excerpt:\n{{content}}', inputSchema: { type:'object', required:['topic','content'], properties:{ topic:{type:'string',title:'Page Topic',placeholder:'e.g. Guide to email marketing'}, keyword:{type:'string',title:'Target Keyword',placeholder:'e.g. email marketing guide'}, existingPages:{type:'string',title:'Existing Site Pages (one per line)',placeholder:'e.g.\nEmail subject line tips\nEmail list building guide\nEmail automation tools'}, content:{type:'string',title:'Content Excerpt',placeholder:'Paste a section of your content here...'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:512, temperature:0.4, creditCost:1 } },
    { name: 'SEO Content Optimizer', slug: 'seo-content-optimizer', description: 'Analyse and optimise existing content for better SEO performance and keyword coverage.', shortDescription: 'Optimise your content for higher rankings.', categorySlug: 'seo', tags: ['seo','optimise','content','ranking'], isPremium: true, isFeatured: true, sortOrder: 8,
      config: { systemPrompt: 'You are an SEO content optimisation expert. Analyse the provided content and give specific, actionable recommendations to improve keyword usage, readability, structure, and overall SEO performance. Provide an optimised rewrite of key sections.', userPromptTemplate: 'Optimise this content for SEO:\n\nTarget keyword: {{keyword}}\nSecondary keywords: {{secondary}}\nCurrent content:\n{{content}}', inputSchema: { type:'object', required:['keyword','content'], properties:{ keyword:{type:'string',title:'Target Keyword',placeholder:'e.g. best project management software'}, secondary:{type:'string',title:'Secondary Keywords',placeholder:'e.g. project management tools, team collaboration'}, content:{type:'string',title:'Content to Optimise',placeholder:'Paste your existing content here...'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:2048, temperature:0.5, creditCost:3 } },
  ];
}

// ─── Social Media Tools ───────────────────────────────────────────────────────

function socialTools(): ToolSeed[] {
  return [
    { name: 'Facebook Post', slug: 'facebook-post', description: 'Write engaging Facebook posts that drive likes, comments, shares, and reach.', shortDescription: 'Create Facebook posts that get engagement.', categorySlug: 'social-media', tags: ['facebook','social','post','engagement'], isPremium: false, isFeatured: false, sortOrder: 0,
      config: { systemPrompt: 'You are a social media expert specialising in Facebook. Write engaging posts that spark conversation, use storytelling, and encourage interaction. Vary between educational, entertaining, and promotional content.', userPromptTemplate: 'Write a Facebook post about:\n\nTopic: {{topic}}\nPost goal: {{goal}}\nBusiness/Brand: {{brand}}\nTone: {{tone}}', inputSchema: { type:'object', required:['topic'], properties:{ topic:{type:'string',title:'Post Topic',placeholder:'e.g. Announcing our new product launch'}, goal:{type:'string',title:'Post Goal',enum:['engagement','awareness','promotion','education','entertainment'],default:'engagement'}, brand:{type:'string',title:'Brand or Business',placeholder:'e.g. FreshBrew Coffee'}, tone:{type:'string',title:'Tone',enum:['fun','professional','inspirational','conversational'],default:'conversational'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:512, temperature:0.8, creditCost:1 } },
    { name: 'Instagram Caption', slug: 'instagram-caption', description: 'Write scroll-stopping Instagram captions with relevant hashtags for maximum reach.', shortDescription: 'Create Instagram captions that get likes.', categorySlug: 'social-media', tags: ['instagram','caption','hashtags','social'], isPremium: false, isFeatured: true, sortOrder: 1,
      config: { systemPrompt: 'You are an Instagram content expert. Write engaging captions that hook readers in the first line, tell a story or provide value, and end with a question or CTA. Include 20-30 relevant hashtags grouped by size.', userPromptTemplate: 'Write an Instagram caption for:\n\nPost topic: {{topic}}\nBrand/Account type: {{brand}}\nTone: {{tone}}\nInclude hashtags: yes', inputSchema: { type:'object', required:['topic'], properties:{ topic:{type:'string',title:'Post Topic',placeholder:'e.g. Morning coffee ritual flat lay photo'}, brand:{type:'string',title:'Brand or Account Type',placeholder:'e.g. Lifestyle brand, fitness coach'}, tone:{type:'string',title:'Tone',enum:['fun','inspirational','educational','aesthetic','bold'],default:'fun'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:512, temperature:0.8, creditCost:1 } },
    { name: 'LinkedIn Post', slug: 'linkedin-post', description: 'Write professional LinkedIn posts that build authority, grow your network, and drive engagement.', shortDescription: 'Create LinkedIn posts that build authority.', categorySlug: 'social-media', tags: ['linkedin','professional','b2b','networking'], isPremium: false, isFeatured: true, sortOrder: 2,
      config: { systemPrompt: 'You are a LinkedIn content strategist. Write professional posts that provide genuine value, share insights or stories, and position the author as a thought leader. Use short paragraphs, line breaks for readability, and end with a question.', userPromptTemplate: 'Write a LinkedIn post about:\n\nTopic: {{topic}}\nKey insight or story: {{insight}}\nTarget audience: {{audience}}\nPost format: {{format}}', inputSchema: { type:'object', required:['topic'], properties:{ topic:{type:'string',title:'Post Topic',placeholder:'e.g. Lessons learned from my first startup failure'}, insight:{type:'string',title:'Key Insight or Story',placeholder:'e.g. I lost $50k but learned these 3 things...'}, audience:{type:'string',title:'Target Audience',placeholder:'e.g. Entrepreneurs and startup founders'}, format:{type:'string',title:'Post Format',enum:['story','tips list','opinion','case study','question'],default:'story'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:512, temperature:0.7, creditCost:1 } },
    { name: 'TikTok Script', slug: 'tiktok-script', description: 'Write viral TikTok video scripts with hooks, content, and CTAs for any niche.', shortDescription: 'Write TikTok scripts that go viral.', categorySlug: 'social-media', tags: ['tiktok','video','script','viral','social'], isPremium: false, isFeatured: true, sortOrder: 3,
      config: { systemPrompt: 'You are a TikTok content creator and scriptwriter. Write short-form video scripts with a powerful hook in the first 3 seconds, engaging content that delivers value fast, and a strong CTA. Format with [HOOK], [CONTENT], and [CTA] sections.', userPromptTemplate: 'Write a TikTok script about:\n\nTopic: {{topic}}\nVideo length: {{length}}\nNiche/Account type: {{niche}}\nHook style: {{hookStyle}}', inputSchema: { type:'object', required:['topic'], properties:{ topic:{type:'string',title:'Video Topic',placeholder:'e.g. 3 productivity hacks that changed my life'}, length:{type:'string',title:'Video Length',enum:['15 seconds','30 seconds','60 seconds'],default:'30 seconds'}, niche:{type:'string',title:'Niche or Account Type',placeholder:'e.g. Business and productivity'}, hookStyle:{type:'string',title:'Hook Style',enum:['question','bold statement','story','controversy','tip reveal'],default:'bold statement'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:512, temperature:0.8, creditCost:1 } },
    { name: 'YouTube Description', slug: 'youtube-description', description: 'Write SEO-optimised YouTube video descriptions that rank in search and drive clicks.', shortDescription: 'Write YouTube descriptions that rank.', categorySlug: 'social-media', tags: ['youtube','video','description','seo'], isPremium: false, isFeatured: false, sortOrder: 4,
      config: { systemPrompt: 'You are a YouTube SEO expert. Write video descriptions with the target keyword in the first 2 lines, a compelling summary, timestamps placeholder, links section, and relevant hashtags. Optimise for both search and viewer engagement.', userPromptTemplate: 'Write a YouTube description for:\n\nVideo title: {{title}}\nVideo topic: {{topic}}\nTarget keyword: {{keyword}}\nChannel niche: {{niche}}', inputSchema: { type:'object', required:['title','topic'], properties:{ title:{type:'string',title:'Video Title',placeholder:'e.g. How I Made $10k in 30 Days with Dropshipping'}, topic:{type:'string',title:'Video Topic',placeholder:'e.g. Dropshipping success story and strategy breakdown'}, keyword:{type:'string',title:'Target Keyword',placeholder:'e.g. dropshipping for beginners'}, niche:{type:'string',title:'Channel Niche',placeholder:'e.g. E-commerce and online business'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:512, temperature:0.6, creditCost:1 } },
    { name: 'Hashtag Generator', slug: 'hashtag-generator', description: 'Generate targeted hashtag sets for Instagram, TikTok, LinkedIn, and Twitter/X.', shortDescription: 'Find the best hashtags for your posts.', categorySlug: 'social-media', tags: ['hashtags','instagram','tiktok','reach','social'], isPremium: false, isFeatured: false, sortOrder: 5,
      config: { systemPrompt: 'You are a social media growth expert. Generate strategic hashtag sets mixing high-volume, medium, and niche hashtags. Group them by size and relevance. Explain the strategy for each group.', userPromptTemplate: 'Generate hashtags for:\n\nPost topic: {{topic}}\nPlatform: {{platform}}\nNiche: {{niche}}\nHashtag count: {{count}}', inputSchema: { type:'object', required:['topic','platform'], properties:{ topic:{type:'string',title:'Post Topic',placeholder:'e.g. Morning workout routine'}, platform:{type:'string',title:'Platform',enum:['Instagram','TikTok','Twitter/X','LinkedIn'],default:'Instagram'}, niche:{type:'string',title:'Niche',placeholder:'e.g. Fitness and wellness'}, count:{type:'string',title:'Number of Hashtags',enum:['10','20','30'],default:'20'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:512, temperature:0.5, creditCost:1 } },
    { name: 'Social Media Ideas', slug: 'social-media-ideas', description: 'Generate a week of creative social media post ideas for any brand or niche.', shortDescription: 'Get a week of social media post ideas.', categorySlug: 'social-media', tags: ['social','ideas','content','planning'], isPremium: false, isFeatured: false, sortOrder: 6,
      config: { systemPrompt: 'You are a social media content strategist. Generate diverse, creative post ideas that mix educational, entertaining, promotional, and engagement content. Include the post type, topic, and a brief description for each idea.', userPromptTemplate: 'Generate social media post ideas for:\n\nBrand/Business: {{brand}}\nPlatform: {{platform}}\nNiche: {{niche}}\nNumber of ideas: {{count}}', inputSchema: { type:'object', required:['brand','niche'], properties:{ brand:{type:'string',title:'Brand or Business',placeholder:'e.g. Organic skincare brand'}, platform:{type:'string',title:'Platform',enum:['Instagram','Facebook','LinkedIn','TikTok','Twitter/X','All platforms'],default:'Instagram'}, niche:{type:'string',title:'Niche',placeholder:'e.g. Natural beauty and skincare'}, count:{type:'string',title:'Number of Ideas',enum:['7','14','21','30'],default:'7'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:1024, temperature:0.8, creditCost:2 } },
    { name: 'Content Calendar', slug: 'content-calendar', description: 'Generate a complete monthly social media content calendar with post ideas and themes.', shortDescription: 'Plan a full month of social content.', categorySlug: 'social-media', tags: ['content-calendar','planning','social','strategy'], isPremium: true, isFeatured: true, sortOrder: 7,
      config: { systemPrompt: 'You are a social media content strategist. Create a detailed monthly content calendar with daily post ideas, content themes, post types, and captions starters. Balance promotional, educational, and engagement content using the 80/20 rule.', userPromptTemplate: 'Create a content calendar for:\n\nBrand/Business: {{brand}}\nPlatform: {{platform}}\nMonth/Theme: {{month}}\nPosting frequency: {{frequency}}\nBusiness goals: {{goals}}', inputSchema: { type:'object', required:['brand','platform'], properties:{ brand:{type:'string',title:'Brand or Business',placeholder:'e.g. Digital marketing agency'}, platform:{type:'string',title:'Primary Platform',enum:['Instagram','Facebook','LinkedIn','TikTok','Multi-platform'],default:'Instagram'}, month:{type:'string',title:'Month or Theme',placeholder:'e.g. January - New Year, New Goals'}, frequency:{type:'string',title:'Posting Frequency',enum:['daily','5x per week','3x per week','every other day'],default:'5x per week'}, goals:{type:'string',title:'Business Goals',placeholder:'e.g. Grow followers, drive website traffic'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:2048, temperature:0.7, creditCost:4 } },
  ];
}

// ─── Other Tools ──────────────────────────────────────────────────────────────

function otherTools(): ToolSeed[] {
  return [
    { name: 'Code Explainer', slug: 'code-explainer', description: 'Paste any code and get a plain-English explanation of what it does.', shortDescription: 'Understand any code instantly.', categorySlug: 'code-development', tags: ['code','explain','debug','learning'], isPremium: false, isFeatured: true, sortOrder: 0,
      config: { systemPrompt: 'You are a senior software engineer and technical writer. Explain code clearly and concisely, covering what it does, how it works, and any potential issues.', userPromptTemplate: 'Explain this code:\n\n```{{language}}\n{{code}}\n```\n\nExplanation level: {{level}}', inputSchema: { type:'object', required:['code'], properties:{ code:{type:'string',title:'Code to Explain',placeholder:'Paste your code here...'}, language:{type:'string',title:'Programming Language',placeholder:'e.g. javascript',default:'javascript'}, level:{type:'string',title:'Explanation Level',enum:['beginner','intermediate','expert'],default:'intermediate'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:1024, temperature:0.3, creditCost:1 } },
    { name: 'Code Generator', slug: 'code-generator', description: 'Describe what you need and get production-ready code.', shortDescription: 'Generate code from a description.', categorySlug: 'code-development', tags: ['code','generate','programming'], isPremium: true, isFeatured: true, sortOrder: 1,
      config: { systemPrompt: 'You are an expert software engineer. Write clean, well-commented, production-ready code following best practices for the specified language and framework.', userPromptTemplate: 'Write code for the following:\n\nTask: {{task}}\nLanguage: {{language}}\nFramework: {{framework}}\nRequirements: {{requirements}}', inputSchema: { type:'object', required:['task','language'], properties:{ task:{type:'string',title:'What to Build',placeholder:'e.g. REST API endpoint for user authentication'}, language:{type:'string',title:'Programming Language',placeholder:'e.g. TypeScript'}, framework:{type:'string',title:'Framework',placeholder:'e.g. NestJS (optional)'}, requirements:{type:'string',title:'Additional Requirements',placeholder:'e.g. Use JWT, include error handling'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:2048, temperature:0.2, creditCost:3 } },
    { name: 'Business Plan Generator', slug: 'business-plan-generator', description: 'Generate a structured business plan outline for any business idea.', shortDescription: 'Turn your idea into a business plan.', categorySlug: 'business-strategy', tags: ['business','startup','planning','strategy'], isPremium: true, isFeatured: true, sortOrder: 0,
      config: { systemPrompt: 'You are a business consultant and startup advisor. Create comprehensive, realistic business plans with executive summaries, market analysis, financial projections, and actionable strategies.', userPromptTemplate: 'Create a business plan for:\n\nBusiness idea: {{idea}}\nIndustry: {{industry}}\nTarget market: {{market}}\nInitial budget: {{budget}}', inputSchema: { type:'object', required:['idea'], properties:{ idea:{type:'string',title:'Business Idea',placeholder:'e.g. AI-powered meal planning app'}, industry:{type:'string',title:'Industry',placeholder:'e.g. Health & Wellness Tech'}, market:{type:'string',title:'Target Market',placeholder:'e.g. Health-conscious millennials'}, budget:{type:'string',title:'Initial Budget',placeholder:'e.g. $50,000'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:3000, temperature:0.6, creditCost:5 } },
  ];
}

// ─── Image Tools ─────────────────────────────────────────────────────────────

function imageTools(): ToolSeed[] {
  return [
    { name: 'AI Image Generator', slug: 'ai-image-generator', description: 'Generate detailed AI image prompts for any scene, style, or concept ready for Midjourney, DALL-E, or Stable Diffusion.', shortDescription: 'Create AI image prompts instantly.', categorySlug: 'image-design', tags: ['image','ai','prompt','midjourney','dalle'], isPremium: false, isFeatured: true, sortOrder: 0,
      config: { systemPrompt: 'You are an expert AI image prompt engineer. Create highly detailed, optimised prompts for AI image generators. Include subject, style, lighting, composition, colour palette, mood, and technical parameters. Output multiple prompt variations.', userPromptTemplate: 'Create AI image prompts for:\n\nSubject/Scene: {{subject}}\nArt style: {{style}}\nAspect ratio: {{aspectRatio}}\nMood/Atmosphere: {{mood}}\nAdditional details: {{details}}', inputSchema: { type:'object', required:['subject'], properties:{ subject:{type:'string',title:'Subject or Scene',placeholder:'e.g. A futuristic city at sunset with flying cars'}, style:{type:'string',title:'Art Style',enum:['photorealistic','digital art','oil painting','watercolour','anime','cinematic','3D render','sketch','minimalist'],default:'photorealistic'}, aspectRatio:{type:'string',title:'Aspect Ratio',enum:['1:1 (square)','16:9 (landscape)','9:16 (portrait)','4:3','3:2'],default:'16:9 (landscape)'}, mood:{type:'string',title:'Mood or Atmosphere',enum:['dramatic','peaceful','mysterious','vibrant','dark','ethereal','warm','cold'],default:'dramatic'}, details:{type:'string',title:'Additional Details',placeholder:'e.g. golden hour lighting, ultra detailed, 8K'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:1024, temperature:0.8, creditCost:2 } },
    { name: 'AI Image Prompt Generator', slug: 'ai-image-prompt-generator', description: 'Turn a simple idea into a highly detailed, optimised prompt for any AI image tool.', shortDescription: 'Turn ideas into perfect image prompts.', categorySlug: 'image-design', tags: ['image','prompt','midjourney','stable-diffusion','dalle'], isPremium: false, isFeatured: false, sortOrder: 1,
      config: { systemPrompt: 'You are a master AI image prompt engineer. Transform simple descriptions into rich, detailed prompts with style modifiers, lighting descriptors, camera settings, and quality boosters. Output 3 prompt variations from simple to ultra-detailed.', userPromptTemplate: 'Transform this idea into AI image prompts:\n\nIdea: {{idea}}\nTarget tool: {{tool}}\nStyle preference: {{style}}\nSize: {{size}}', inputSchema: { type:'object', required:['idea'], properties:{ idea:{type:'string',title:'Your Idea',placeholder:'e.g. A cozy coffee shop on a rainy day',required:true}, tool:{type:'string',title:'AI Image Tool',enum:['Midjourney','DALL-E 3','Stable Diffusion','Adobe Firefly','Any'],default:'Midjourney'}, style:{type:'string',title:'Style Preference',enum:['photorealistic','artistic','cartoon','fantasy','sci-fi','vintage','modern'],default:'photorealistic'}, size:{type:'string',title:'Image Size',enum:['1024x1024','1792x1024','1024x1792','512x512'],default:'1024x1024'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:1024, temperature:0.8, creditCost:1 } },
    { name: 'Product Image Prompt', slug: 'product-image-prompt', description: 'Generate professional product photography prompts for e-commerce, ads, and marketing.', shortDescription: 'Create product photo prompts for AI.', categorySlug: 'image-design', tags: ['product','photography','ecommerce','prompt','image'], isPremium: false, isFeatured: false, sortOrder: 2,
      config: { systemPrompt: 'You are a professional product photographer and AI prompt specialist. Create detailed prompts for product photography that highlight the product beautifully with professional lighting, clean backgrounds, and commercial-quality composition.', userPromptTemplate: 'Create product image prompts for:\n\nProduct: {{product}}\nBackground style: {{background}}\nLighting: {{lighting}}\nAspect ratio: {{aspectRatio}}\nNumber of prompts: 3', inputSchema: { type:'object', required:['product'], properties:{ product:{type:'string',title:'Product Description',placeholder:'e.g. Minimalist white ceramic coffee mug'}, background:{type:'string',title:'Background Style',enum:['pure white','gradient','lifestyle setting','studio','natural outdoor','dark moody'],default:'pure white'}, lighting:{type:'string',title:'Lighting Style',enum:['soft studio','natural window light','dramatic side light','flat lay overhead','golden hour'],default:'soft studio'}, aspectRatio:{type:'string',title:'Aspect Ratio',enum:['1:1 (square)','4:3','16:9','3:4 (portrait)'],default:'1:1 (square)'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:768, temperature:0.7, creditCost:1 } },
    { name: 'Social Media Image Prompt', slug: 'social-media-image-prompt', description: 'Generate optimised AI image prompts sized and styled for each social media platform.', shortDescription: 'Create social media visuals with AI prompts.', categorySlug: 'image-design', tags: ['social','image','prompt','instagram','facebook'], isPremium: false, isFeatured: false, sortOrder: 3,
      config: { systemPrompt: 'You are a social media visual content expert and AI prompt engineer. Create platform-optimised image prompts that are eye-catching, on-brand, and sized correctly for each social platform. Include style, composition, and engagement-boosting visual elements.', userPromptTemplate: 'Create social media image prompts for:\n\nContent topic: {{topic}}\nPlatform: {{platform}}\nBrand style: {{brandStyle}}\nColour palette: {{colours}}', inputSchema: { type:'object', required:['topic','platform'], properties:{ topic:{type:'string',title:'Content Topic',placeholder:'e.g. New product launch announcement'}, platform:{type:'string',title:'Platform',enum:['Instagram Post (1:1)','Instagram Story (9:16)','Facebook Post','LinkedIn Post','Twitter/X Post','Pinterest Pin'],default:'Instagram Post (1:1)'}, brandStyle:{type:'string',title:'Brand Style',enum:['modern & minimal','bold & vibrant','elegant & luxury','fun & playful','professional & corporate'],default:'modern & minimal'}, colours:{type:'string',title:'Colour Palette',placeholder:'e.g. navy blue, gold, white'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:768, temperature:0.8, creditCost:1 } },
    { name: 'Ad Creative Generator', slug: 'ad-creative-generator', description: 'Generate AI image prompts for high-converting ad creatives for Facebook, Google, and display ads.', shortDescription: 'Create ad creative prompts with AI.', categorySlug: 'image-design', tags: ['ads','creative','image','prompt','marketing'], isPremium: true, isFeatured: true, sortOrder: 4,
      config: { systemPrompt: 'You are a performance marketing creative director and AI prompt specialist. Create compelling ad creative prompts that grab attention, communicate the value proposition visually, and drive clicks. Include copy overlay suggestions and CTA placement.', userPromptTemplate: 'Create ad creative prompts for:\n\nProduct/Service: {{product}}\nAd platform: {{platform}}\nTarget audience: {{audience}}\nKey message: {{message}}\nAd size: {{size}}', inputSchema: { type:'object', required:['product','platform'], properties:{ product:{type:'string',title:'Product or Service',placeholder:'e.g. Premium fitness app subscription'}, platform:{type:'string',title:'Ad Platform',enum:['Facebook/Instagram Feed','Facebook/Instagram Story','Google Display','YouTube Thumbnail','LinkedIn Sponsored'],default:'Facebook/Instagram Feed'}, audience:{type:'string',title:'Target Audience',placeholder:'e.g. Fitness enthusiasts aged 25-40'}, message:{type:'string',title:'Key Message',placeholder:'e.g. Transform your body in 30 days'}, size:{type:'string',title:'Ad Size',enum:['1:1 (1080x1080)','9:16 (1080x1920)','16:9 (1920x1080)','4:5 (1080x1350)'],default:'1:1 (1080x1080)'} } }, outputFormat:'text', aiModel:'gpt-4o', maxTokens:1024, temperature:0.8, creditCost:2 } },
  ];
}

// ─── Extended Code Tools ──────────────────────────────────────────────────────

function codeExtendedTools(): ToolSeed[] {
  return [
    { name: 'Bug Fixer', slug: 'bug-fixer', description: 'Paste buggy code and get a fixed version with a clear explanation of what was wrong.', shortDescription: 'Fix bugs in any code instantly.', categorySlug: 'code-development', tags: ['code','debug','fix','bug','programming'], isPremium: false, isFeatured: true, sortOrder: 2,
      config: { systemPrompt: 'You are an expert software debugger. Identify all bugs, errors, and issues in the provided code. Return the fixed code with clear comments explaining each fix, and a summary of all issues found.', userPromptTemplate: 'Fix the bugs in this code:\n\n```{{language}}\n{{code}}\n```\n\nError message (if any): {{error}}\nExpected behaviour: {{expected}}', inputSchema: { type:'object', required:['code'], properties:{ code:{type:'string',title:'Buggy Code',placeholder:'Paste your code here...'}, language:{type:'string',title:'Programming Language',placeholder:'e.g. TypeScript',default:'javascript'}, error:{type:'string',title:'Error Message',placeholder:'e.g. TypeError: Cannot read property of undefined'}, expected:{type:'string',title:'Expected Behaviour',placeholder:'e.g. Should return user object from database'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:2048, temperature:0.2, creditCost:2 } },
    { name: 'SQL Generator', slug: 'sql-generator', description: 'Generate SQL queries from plain English descriptions for any database schema.', shortDescription: 'Write SQL queries from plain English.', categorySlug: 'code-development', tags: ['sql','database','query','code'], isPremium: false, isFeatured: false, sortOrder: 3,
      config: { systemPrompt: 'You are a senior database engineer. Write clean, optimised SQL queries from natural language descriptions. Include comments explaining complex parts, and suggest indexes if relevant.', userPromptTemplate: 'Write a SQL query for:\n\nTask: {{task}}\nDatabase type: {{dbType}}\nTable schema:\n{{schema}}\nAdditional requirements: {{requirements}}', inputSchema: { type:'object', required:['task'], properties:{ task:{type:'string',title:'What the Query Should Do',placeholder:'e.g. Get all users who signed up in the last 30 days with their order count'}, dbType:{type:'string',title:'Database Type',enum:['PostgreSQL','MySQL','SQLite','SQL Server','Oracle'],default:'PostgreSQL'}, schema:{type:'string',title:'Table Schema (optional)',placeholder:'e.g. users(id, email, created_at), orders(id, user_id, total, created_at)'}, requirements:{type:'string',title:'Additional Requirements',placeholder:'e.g. Sort by signup date, limit to 100 results'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:1024, temperature:0.2, creditCost:1 } },
    { name: 'Regex Generator', slug: 'regex-generator', description: 'Generate regular expressions from plain English with explanations and test cases.', shortDescription: 'Create regex patterns from descriptions.', categorySlug: 'code-development', tags: ['regex','code','pattern','validation'], isPremium: false, isFeatured: false, sortOrder: 4,
      config: { systemPrompt: 'You are a regex expert. Generate accurate regular expressions from natural language descriptions. Provide the regex pattern, a plain English explanation of how it works, and 5 test cases showing matches and non-matches.', userPromptTemplate: 'Generate a regex for:\n\nDescription: {{description}}\nLanguage/Flavour: {{language}}\nTest examples: {{examples}}', inputSchema: { type:'object', required:['description'], properties:{ description:{type:'string',title:'What to Match',placeholder:'e.g. Valid email addresses'}, language:{type:'string',title:'Language or Flavour',enum:['JavaScript','Python','PHP','Java','Go','PCRE (general)'],default:'JavaScript'}, examples:{type:'string',title:'Example Strings to Match',placeholder:'e.g. user@example.com, test.name+tag@domain.co.uk'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:768, temperature:0.1, creditCost:1 } },
    { name: 'API Generator', slug: 'api-generator', description: 'Generate complete REST API endpoint code with routes, controllers, validation, and error handling.', shortDescription: 'Generate REST API endpoints instantly.', categorySlug: 'code-development', tags: ['api','rest','code','backend','generate'], isPremium: true, isFeatured: true, sortOrder: 5,
      config: { systemPrompt: 'You are a senior backend engineer. Generate complete, production-ready REST API endpoint code with proper HTTP methods, request validation, error handling, response formatting, and inline documentation.', userPromptTemplate: 'Generate a REST API endpoint for:\n\nEndpoint purpose: {{purpose}}\nHTTP method: {{method}}\nLanguage/Framework: {{framework}}\nRequest body/params: {{input}}\nResponse format: {{output}}', inputSchema: { type:'object', required:['purpose','framework'], properties:{ purpose:{type:'string',title:'Endpoint Purpose',placeholder:'e.g. Create a new user with email and password'}, method:{type:'string',title:'HTTP Method',enum:['GET','POST','PUT','PATCH','DELETE'],default:'POST'}, framework:{type:'string',title:'Language / Framework',enum:['NestJS (TypeScript)','Express (TypeScript)','Express (JavaScript)','FastAPI (Python)','Django REST','Laravel (PHP)'],default:'NestJS (TypeScript)'}, input:{type:'string',title:'Request Body / Params',placeholder:'e.g. { email: string, password: string, name: string }'}, output:{type:'string',title:'Response Format',placeholder:'e.g. { success: true, data: { userId, token } }'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:2048, temperature:0.2, creditCost:3 } },
    { name: 'Documentation Generator', slug: 'documentation-generator', description: 'Generate clear, comprehensive documentation for any code, function, or API.', shortDescription: 'Auto-generate code documentation.', categorySlug: 'code-development', tags: ['docs','documentation','code','jsdoc','readme'], isPremium: false, isFeatured: false, sortOrder: 6,
      config: { systemPrompt: 'You are a technical writer and senior developer. Generate clear, comprehensive documentation including function descriptions, parameter types, return values, usage examples, and edge cases. Follow the documentation style for the specified language.', userPromptTemplate: 'Generate documentation for:\n\n```{{language}}\n{{code}}\n```\n\nDoc style: {{docStyle}}\nInclude examples: yes', inputSchema: { type:'object', required:['code'], properties:{ code:{type:'string',title:'Code to Document',placeholder:'Paste your function, class, or API code here...'}, language:{type:'string',title:'Programming Language',placeholder:'e.g. TypeScript',default:'TypeScript'}, docStyle:{type:'string',title:'Documentation Style',enum:['JSDoc','TSDoc','Python Docstring','Markdown README','OpenAPI/Swagger','Inline comments'],default:'TSDoc'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:1024, temperature:0.3, creditCost:1 } },
  ];
}

// ─── Productivity Tools ───────────────────────────────────────────────────────

function productivityTools(): ToolSeed[] {
  return [
    { name: 'Meeting Summarizer', slug: 'meeting-summarizer', description: 'Paste meeting notes or transcripts and get a structured summary with action items and decisions.', shortDescription: 'Summarize meetings with action items.', categorySlug: 'productivity', tags: ['meeting','summary','productivity','notes','action-items'], isPremium: false, isFeatured: true, sortOrder: 0,
      config: { systemPrompt: 'You are an expert meeting facilitator and note-taker. Summarize meeting content into a structured format with: Executive Summary, Key Discussion Points, Decisions Made, Action Items (with owners if mentioned), and Next Steps.', userPromptTemplate: 'Summarize this meeting:\n\nMeeting context: {{context}}\nMeeting notes/transcript:\n{{notes}}\n\nOutput format: {{format}}', inputSchema: { type:'object', required:['notes'], properties:{ notes:{type:'string',title:'Meeting Notes or Transcript',placeholder:'Paste your meeting notes or transcript here...'}, context:{type:'string',title:'Meeting Context',placeholder:'e.g. Weekly product team standup, Q4 planning session'}, format:{type:'string',title:'Output Format',enum:['structured summary','bullet points','executive brief','action items only'],default:'structured summary'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:1024, temperature:0.3, creditCost:2 } },
    { name: 'Task Generator', slug: 'task-generator', description: 'Break down any project or goal into a structured list of actionable tasks with priorities.', shortDescription: 'Break goals into actionable tasks.', categorySlug: 'productivity', tags: ['tasks','productivity','planning','project','todo'], isPremium: false, isFeatured: false, sortOrder: 1,
      config: { systemPrompt: 'You are a project management expert. Break down goals and projects into clear, actionable tasks with priorities, estimated time, and logical sequencing. Group tasks by phase or category.', userPromptTemplate: 'Generate tasks for:\n\nGoal/Project: {{goal}}\nContext: {{context}}\nTimeframe: {{timeframe}}\nOutput format: {{format}}', inputSchema: { type:'object', required:['goal'], properties:{ goal:{type:'string',title:'Goal or Project',placeholder:'e.g. Launch a new SaaS product landing page'}, context:{type:'string',title:'Context',placeholder:'e.g. Solo founder, limited budget, 2-person team'}, timeframe:{type:'string',title:'Timeframe',enum:['1 day','1 week','2 weeks','1 month','3 months'],default:'1 week'}, format:{type:'string',title:'Output Format',enum:['numbered list with priorities','kanban columns (To Do / In Progress / Done)','phased plan','simple checklist'],default:'numbered list with priorities'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:1024, temperature:0.5, creditCost:1 } },
    { name: 'Brainstorming Assistant', slug: 'brainstorming-assistant', description: 'Generate creative ideas, solutions, and perspectives for any problem or opportunity.', shortDescription: 'Generate creative ideas for any challenge.', categorySlug: 'productivity', tags: ['brainstorm','ideas','creativity','problem-solving','innovation'], isPremium: false, isFeatured: true, sortOrder: 2,
      config: { systemPrompt: 'You are a creative thinking facilitator and innovation expert. Generate diverse, creative ideas using multiple thinking frameworks (lateral thinking, SCAMPER, reverse brainstorming, analogical thinking). Push beyond obvious solutions.', userPromptTemplate: 'Brainstorm ideas for:\n\nChallenge/Opportunity: {{challenge}}\nContext: {{context}}\nConstraints: {{constraints}}\nIdea quantity: {{quantity}}\nTone: {{tone}}', inputSchema: { type:'object', required:['challenge'], properties:{ challenge:{type:'string',title:'Challenge or Opportunity',placeholder:'e.g. How to increase user retention for our app'}, context:{type:'string',title:'Context',placeholder:'e.g. B2B SaaS, 500 monthly active users, churn rate 15%'}, constraints:{type:'string',title:'Constraints',placeholder:'e.g. No budget for paid ads, team of 3'}, quantity:{type:'string',title:'Number of Ideas',enum:['10','20','30'],default:'20'}, tone:{type:'string',title:'Tone',enum:['practical','creative & wild','balanced','strategic'],default:'balanced'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:1024, temperature:0.9, creditCost:2 } },
    { name: 'Presentation Outline', slug: 'presentation-outline', description: 'Generate a structured presentation outline with slide titles, key points, and speaker notes.', shortDescription: 'Create presentation outlines instantly.', categorySlug: 'productivity', tags: ['presentation','slides','outline','productivity','pitch'], isPremium: false, isFeatured: false, sortOrder: 3,
      config: { systemPrompt: 'You are a presentation design expert and public speaking coach. Create compelling presentation outlines with a strong opening hook, logical flow, persuasive content structure, and memorable closing. Include slide titles, 3-5 bullet points per slide, and brief speaker notes.', userPromptTemplate: 'Create a presentation outline for:\n\nTopic: {{topic}}\nAudience: {{audience}}\nPresentation goal: {{goal}}\nNumber of slides: {{slides}}\nTone: {{tone}}', inputSchema: { type:'object', required:['topic'], properties:{ topic:{type:'string',title:'Presentation Topic',placeholder:'e.g. Q4 marketing strategy review'}, audience:{type:'string',title:'Audience',placeholder:'e.g. C-suite executives, investors'}, goal:{type:'string',title:'Presentation Goal',enum:['inform','persuade','inspire','pitch','train','report'],default:'inform'}, slides:{type:'string',title:'Number of Slides',enum:['5','8','10','15','20'],default:'10'}, tone:{type:'string',title:'Tone',enum:['professional','conversational','inspiring','data-driven'],default:'professional'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:1024, temperature:0.6, creditCost:2 } },
    { name: 'Business Idea Generator', slug: 'business-idea-generator', description: 'Generate validated business ideas based on your skills, interests, and market opportunities.', shortDescription: 'Discover profitable business ideas.', categorySlug: 'productivity', tags: ['business','ideas','startup','entrepreneurship','innovation'], isPremium: false, isFeatured: false, sortOrder: 4,
      config: { systemPrompt: 'You are a serial entrepreneur and business strategist. Generate creative, viable business ideas with market validation signals, target customers, revenue model, and initial steps to validate. Focus on ideas with real market demand.', userPromptTemplate: 'Generate business ideas based on:\n\nSkills/Expertise: {{skills}}\nInterests: {{interests}}\nBudget range: {{budget}}\nBusiness model preference: {{model}}\nNumber of ideas: {{count}}', inputSchema: { type:'object', required:['skills'], properties:{ skills:{type:'string',title:'Your Skills or Expertise',placeholder:'e.g. Web development, marketing, writing'}, interests:{type:'string',title:'Your Interests',placeholder:'e.g. Fitness, technology, education'}, budget:{type:'string',title:'Starting Budget',enum:['$0 (bootstrapped)','Under $1,000','$1,000-$10,000','$10,000+'],default:'Under $1,000'}, model:{type:'string',title:'Business Model',enum:['SaaS','service/freelance','e-commerce','content/media','marketplace','any'],default:'any'}, count:{type:'string',title:'Number of Ideas',enum:['5','10','15'],default:'10'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:1024, temperature:0.8, creditCost:2 } },
    { name: 'Decision Assistant', slug: 'decision-assistant', description: 'Get a structured analysis to help you make better decisions using proven frameworks.', shortDescription: 'Make better decisions with AI analysis.', categorySlug: 'productivity', tags: ['decision','analysis','productivity','strategy','framework'], isPremium: false, isFeatured: false, sortOrder: 5,
      config: { systemPrompt: 'You are a strategic decision-making expert. Analyse decisions using structured frameworks (pros/cons, decision matrix, risk analysis, second-order thinking). Present a balanced analysis and a clear recommendation with reasoning.', userPromptTemplate: 'Help me decide:\n\nDecision to make: {{decision}}\nContext: {{context}}\nOptions being considered: {{options}}\nKey criteria: {{criteria}}\nAnalysis framework: {{framework}}', inputSchema: { type:'object', required:['decision'], properties:{ decision:{type:'string',title:'Decision to Make',placeholder:'e.g. Should I quit my job to start a business?'}, context:{type:'string',title:'Context',placeholder:'e.g. 5 years experience, $20k savings, family of 3'}, options:{type:'string',title:'Options Being Considered',placeholder:'e.g. Option A: Quit now. Option B: Start part-time first. Option C: Stay.'}, criteria:{type:'string',title:'Key Decision Criteria',placeholder:'e.g. Financial security, personal fulfilment, risk tolerance'}, framework:{type:'string',title:'Analysis Framework',enum:['pros & cons','decision matrix','risk analysis','second-order thinking','full analysis'],default:'full analysis'} } }, outputFormat:'markdown', aiModel:'gpt-4o', maxTokens:1024, temperature:0.5, creditCost:2 } },
  ];
}

// ─── Admin User ───────────────────────────────────────────────────────────────

async function seedAdminUser() {
  const email = 'admin@crackncode.ai';
  const existing = await prisma.user.findUnique({ where: { email } });
  if (existing) { console.log('  ✓ Admin user already exists, skipping'); return; }

  const passwordHash = await bcrypt.hash('Admin@123456', 12);
  const adminRole = await prisma.role.findUnique({ where: { name: 'admin' } });
  const freePlan  = await prisma.plan.findUnique({ where: { tier: 'free' } });

  const admin = await prisma.user.create({
    data: {
      email, passwordHash, role: 'admin', isEmailVerified: true,
      profile:       { create: { name: 'CracknCode Admin', timezone: 'UTC', locale: 'en' } },
      creditAccount: { create: { balance: 9999 } },
      subscription:  freePlan ? { create: { planId: freePlan.id, status: 'active' } } : undefined,
    },
  });

  if (adminRole) {
    await prisma.userRoleAssignment.create({ data: { userId: admin.id, roleId: adminRole.id } });
  }

  console.log(`  ✓ Admin user created: ${email} / Admin@123456`);
  console.log('  ⚠  Change the admin password immediately after first login!');
}

// ─── Run ──────────────────────────────────────────────────────────────────────

main()
  .catch((e) => { console.error('❌ Seed failed:', e); process.exit(1); })
  .finally(() => prisma.$disconnect());
